### ISSUE TITLE
Injection isn't working correctly on prediction page on the routing branch 

### ISSUE THREAD

**Issue by berkmolla** [neil-justice/Tiresias#17]
It seems to fetch the wrong file - it ends up fetching index.ejs again, thinking it's new.html, and can't find login.html at all. So it's likely a case of messed up paths again but will have to investigate.

The buttons work as they're supposed to on the home page.

**Comment by neil-justice** [comment]
fixed this just now - the scripts were inserting "login.html" instead of "/login.html" (and same for new)

**Comment by berkmolla** [comment]
Well played.

**Comment by neil-justice** [comment]
its looking really good now
