### ISSUE TITLE
Space between navbar and login window

### ISSUE THREAD

**Issue by berkmolla** [neil-justice/Tiresias#18]
<img width="1440" alt="screen shot 2016-03-08 at 10 40 40" src="https://cloud.githubusercontent.com/assets/5549405/13603099/b36809ae-e532-11e5-8b49-5c9020b247da.png">

Not only on the first press as we thought yesterday

**Comment by neil-justice** [comment]
seems limited to chrome and safari.  firefox and ie are fine

**Comment by neil-justice** [comment]
i think setting a hardcoded height for the slider-wrapper might help.  right now its being calculated from its children (the inputs and labels).
